rootProject.name = "completable-reactor"
include("completable-reactor-example")
include("completable-reactor-graph")
include("completable-reactor-graph-kotlin")
include("completable-reactor-graph-viewer")
include("completable-reactor-graph-viewer-app")
include("completable-reactor-model")
include("completable-reactor-parser")
include("completable-reactor-runtime")
include("completable-reactor-spring")
include("completable-reactor-test-utils")
