== Best Practice and Code Convention
[abstract]
Paragraph explains handy rules that will keep your code clear.

=== Give your payloads and graphs similar names
It is good to follow same naming convention in the project. 
This way it would be easy to find payloads that could be submitted to reactor 
and graphs that implements their execution flows.  
We can use `ActionNamePayload` and `ActionNameGraph` template for names. 

Bad:
[code,java]
----
class BuyData {...}
class PurchaseConfiguration extends Graph<BuyData> {...}

class SubscriptonAction {...}
class SubscriptonGraphDeclaration extends Graph<SubscriptonAction> {...}
----

Good:

[code,java]
----
class PurchasePayload {...}
class PurchaseGraph extends Graph<PurchasePayload> {...}

class SubscriptonPayload {...}
class SubscriptonGraph extends Graph<SubscriptonPayload.> {...}
----

=== Give your payloads and graphs names that represent actions that graph implies

It is better to give graph a name that represent action. 

[code,java]
----
class SmsSenderPayload {...}
----

Good:

[code,java]
----
class SendSmsPayload {...}
----

=== Treat vertex declaration as a function
Do not wrap your logic into function if the only purpose of the function is to
be invoked inside handler/merger block of a Vertex.
If you are not reusing this function in other places - simply put code inside
handler/merger lambda directly and give the Vertex same name as you would give
to the function.

Bad:
[code,java]
----
public class PurchaseGraph extends Graph<PurchasePayload> {

    Vertex writeUserLog =
        handler(
            //# log ussd purchase
            payload -> writeUserLog(payload)

        ).withMerger((payload, result) -> {
              ...
        });

    Vertex fireSubscribeAction =
        handler(
              //# fire purchase statistic event
              payload -> fireSubscribeAction(payload)

        ).withoutMerger();

    private CompletableFuture<Reullt> writeUserLog(PurchasePayload p) {
        <purchase logging code>
    }

    private CompletableFuture<Void> fireSubscribeAction(PurchasePayload payload) {
            <statistc event firing code>
    }

}

----

Good:

[code,java]
----
public class PurchaseGraph extends Graph<PurchasePayload> {
  Vertex writeUserLog =
      handler(
          //# log ussd purchase
          payload -> {
              <purchase logging code>
          }

      ).withMerger((payload, result) -> {
            ...
      });

  Vertex fireSubscribeAction =
      handler(
            //# fire purchase statistic event
            payload -> {
                <statistc event firing code>
            }

      ).withoutMerger();

}

----

=== Give vertex a name as if it is a function
Vertex usually implies business logic that should be executed as a part of 
use case scenario. 
It would be better to give vertex a name 
that describes what action this vertex implements.     

Bad:

[code,java]
----
Vertex userLogWriter = ...;
Vertex statisticProcessor = ...;
----

Good:

[code,java]
----
Vertex writePurchaseToUserLog = ...;
Vertex firePurchaseEventToStatistics = ...;
----

=== In Spring project declare your graph as a Bean
You can use different approaches in registering graphs in you application. 
Main thing is to be consistent about it. 
We suggest to use an approach when you declare graph as a Bean

[code,java]
----
public class MyGraph extends Graph<MyPayload>{
    @Autowired
    MyService myService;

    Vertex doStuff =
        handler(
            paylaod -> myService.doSomethingUsefull()

        ).withMerger(...);
}

@Configuration
public class ApplicationConfiguration{

    @Bean
    public MyGraph muGraph(){
        return new MyGraph();
    }
    ...

    @Autowired
    Collection<Graph> applicationGraphs;

    @Bean
    public CompletableReactor completableReactor(){
      CompletableReactor completableReactor = new CompletableReactor()
      applicationGraphs.forEach(completableReactor::registerGraph)
      return completableReactor;
    }
}
----

=== Optional, lateinit vars for Graph context variable

Nullable types `T?` or `Optional<T>` force us to check value for null before we can use it.
This is very handy for function arguments, class states, etc.
But lets discuss situation with graphs.
We usually desing graphs in a way so upper vertices initialize data and bottom vertices uses them.
Upper vertex1 initialize `data` with value and vertex2 reads `data`. 
In that case our graph design imply that data will be ready for reading in vertex2. 
Suppose that data is not ready : vertex2 from our example have only one case: if `data` is null - rise an exception. 
But Kotlin lateinit or Nullable `data` will rise NPE for this case for us.
So if our graph design imply that data should be ready before reading by bottom vertices - we should use nullable or lateinit vars.
 
What if our logic have two cases: in one we use data, and in another - do not. 
Best way to solve this case is to try to implement it thought graph design and have two branches of vertices.
This way we can continue to use lateinit vars/nullable values inside payload.   

But some times it is better not to increase complexity by adding new branches to graph
 and instead to use `T?/Optional<T>` data in graph payload. 
Then we simply implement `if (data == null/isPresent) A else B` logic inside vertex without any exceptions.

=== Code formatting
(1) Separate vertex field declaration and handler block with new line '\n' +
(2) Separate handler block and merger block with new line '\n' +
(3) Separate documentation comment with new line '\n' +

[code,java]
----
public class PurchaseGraph extends Graph<PurchasePayload> {
  Vertex writeUserLog =  //(1)
      handler(
          //# log ussd purchase details //(3)
          payload -> {
              <purchase logging code>
          }
      ).withMerger((payload, result) -> { //(2)
            ...
      });

  Vertex fireSubscribeAction =
      handler( payload -> { //(3)
                <statistc event firing code>
            }
      ).withoutMerger();
}
----
